/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author 52292234X
 */
public class pergunta1 extends javax.swing.JFrame {

    int vidas = 3;
    int pontos = 0;
    int i = 0;
    int acertos = 0;
    int erros = 0;

    /**
     * Creates new form pergunta1
     */
    public pergunta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jVida = new javax.swing.JLabel();
        pergunta = new javax.swing.JLabel();
        altA = new javax.swing.JRadioButton();
        altB = new javax.swing.JRadioButton();
        altD = new javax.swing.JRadioButton();
        altC = new javax.swing.JRadioButton();
        btn = new javax.swing.JButton();
        jPontos = new javax.swing.JLabel();
        msgFinal = new javax.swing.JLabel();
        jbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jtitulo.setForeground(new java.awt.Color(255, 0, 0));
        jtitulo.setText("PERGUNTAS");
        getContentPane().add(jtitulo);
        jtitulo.setBounds(250, 50, 220, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("VIDAS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 90, 20);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("PONTOS:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 10, 80, 20);

        jVida.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jVida.setForeground(new java.awt.Color(255, 255, 255));
        jVida.setText("3");
        getContentPane().add(jVida);
        jVida.setBounds(130, 10, 100, 20);

        pergunta.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        pergunta.setForeground(new java.awt.Color(255, 255, 255));
        pergunta.setText("1 - Quantos litros de sangue uma pessoa saúdavel tem?");
        getContentPane().add(pergunta);
        pergunta.setBounds(0, 100, 770, 40);

        buttonGroup1.add(altA);
        altA.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        altA.setForeground(new java.awt.Color(255, 255, 255));
        altA.setText("2 à 4 Litros");
        altA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altAActionPerformed(evt);
            }
        });
        getContentPane().add(altA);
        altA.setBounds(80, 160, 290, 29);

        buttonGroup1.add(altB);
        altB.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        altB.setForeground(new java.awt.Color(255, 255, 255));
        altB.setText("4 à 6 Litros");
        altB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altBActionPerformed(evt);
            }
        });
        getContentPane().add(altB);
        altB.setBounds(80, 200, 290, 29);

        buttonGroup1.add(altD);
        altD.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        altD.setForeground(new java.awt.Color(255, 255, 255));
        altD.setText(" Tem 7 litros");
        altD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altDActionPerformed(evt);
            }
        });
        getContentPane().add(altD);
        altD.setBounds(80, 280, 290, 30);

        buttonGroup1.add(altC);
        altC.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        altC.setForeground(new java.awt.Color(255, 255, 255));
        altC.setText(" Tem 10 litros");
        altC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altCActionPerformed(evt);
            }
        });
        getContentPane().add(altC);
        altC.setBounds(80, 240, 290, 30);

        btn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn.setText("Avançar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn);
        btn.setBounds(550, 310, 101, 30);

        jPontos.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPontos.setForeground(new java.awt.Color(255, 255, 255));
        jPontos.setText("0");
        getContentPane().add(jPontos);
        jPontos.setBounds(620, 9, 70, 21);

        msgFinal.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        msgFinal.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(msgFinal);
        msgFinal.setBounds(50, 180, 630, 60);

        jbackground.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jbackground.setForeground(new java.awt.Color(255, 255, 255));
        jbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        getContentPane().add(jbackground);
        jbackground.setBounds(0, -10, 770, 560);

        setSize(new java.awt.Dimension(813, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void altAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altAActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_altAActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:

        i++;
        switch (i) {
             /****           questão 1             ****/
            case 1:
                jVida.setText(Integer.toString(3));
                if (altB.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));
                    acertos = acertos+1;

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros + 1;
                }
                pergunta.setText("2 - De onde vem a invenção do chuveiro?");
                altA.setText("França");
                altB.setText("Inglaterra");
                altC.setText("Brasil");
                altD.setText("Austrália");
                break;

             /****           questão 2             ****/
            case 2:                
                if (altC.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));   
                    acertos = acertos + 1;                  

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros + 1;

                }
                pergunta.setText("3 - Qual o menor e o maior país do mundo?");
                altA.setText("Vaticano e Rússia");
                altB.setText("Nauru e China");
                altC.setText("Mônaco e Canadá");
                altD.setText("Malta e Estados Unidos");
                break;

                
             /****           questão 3             ****/
            case 3:
                if (altA.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));    
                    acertos = acertos + 1;

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros + 1;
                    
                        if (vidas==0){     
                            gameover fim = new gameover ();
                            fim.setVisible(true);
                            dispose ();
                    }
                }
                pergunta.setText("4 - Qual o livro mais vendido no mundo a seguir à Bíblia?");
                    altA.setText("O senhor dos Anéis");
                    altB.setText("Um conto de duas cidades");
                    altC.setText("O pequeno Príncipe");
                    altD.setText("Dom Quixote");                   
                break;

                
            /****           questão 4             ****/
            case 4:
                if (altD.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));
                    acertos = acertos + 1;                   

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros + 1;
                    
                        if(vidas==0){
                            gameover fim = new gameover ();
                            fim.setVisible(true);
                            dispose ();
                    }
                }
                pergunta.setText("5 - Quantos elementos químicos possui a tabela periódica?");
                    altA.setText("113");
                    altB.setText("109");
                    altC.setText("108");
                    altD.setText("118");
                break;
                
                
                  /****           questão 5             ****/
                case 5:
                if (altD.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));   
                    acertos = acertos+1;

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros+1;
                    
                        if (vidas==0){
                            gameover fim = new gameover ();
                            fim.setVisible(true);
                            dispose ();                    
                    }
                }
                pergunta.setText("6 - Quais países que têm a maior e a menor expectativa de vida?  ");
                    altA.setText("Estados Unidos e Angola");
                    altB.setText("Japão e Serra Leoa");
                    altC.setText("Austrália e Afeganistão");
                    altD.setText("Itália e Chade");
                break;       
                
                
                  /****           questão 6             ****/                
                case 6:
                if (altB.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));
                    acertos = acertos+1;                    

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros+1;
                    
                    if (vidas==0){                      
                        gameover fim = new gameover ();
                        fim.setVisible(true);
                        dispose ();
                    }
                }
                pergunta.setText("7 - O que a palavra legend significa em português?  ");
                    altA.setText("Legenda");
                    altB.setText("Conto");
                    altC.setText("Lenda");
                    altD.setText("Legendário");
                break;
                
                
                 /****           questão 7             ****/
                case 7:
                if (altC.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));
                    acertos = acertos+1;                   

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros+1;
                    
                    if (vidas==0){                       
                        gameover fim = new gameover ();
                        fim.setVisible(true);
                        dispose ();
                    }
                }
                pergunta.setText("8 - Quanto tempo a luz do Sol demora para chegar à Terra?  ");
                    altA.setText("12 minutos");
                    altB.setText("8 minutos");
                    altC.setText("12 horas");
                    altD.setText("1 dia");
                break;
                
                
                /****           questão 8             ****/
                 case 8:
                if (altB.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));
                    acertos = acertos+1;                   

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros+1;                    
                        if (vidas==0){                        
                            gameover fim = new gameover ();
                            fim.setVisible(true);
                            dispose ();
                          }
                }
                pergunta.setText("9 - Qual a nacionalidade de Che Guevara?  ");
                    altA.setText("Cubana");
                    altB.setText("Boliviana");
                    altC.setText("Argentina");
                    altD.setText("Peruana");
                break;
                
                
                 /****           questão 9             ****/
                case 9:
                if (altA.isSelected()) {
                    pontos = pontos + 1;
                    jPontos.setText(Integer.toString(pontos));
                    acertos = acertos+1;                    

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros+1;
                    
                    if (vidas==0){                        
                        gameover fim = new gameover ();
                        fim.setVisible(true);
                        dispose ();
                    }
                }
                pergunta.setText("10 - Em que período da pré-história o fogo foi descoberto?  ");
                    altA.setText("Neolítico");
                    altB.setText("Paleolítico");
                    altC.setText("Neolítico");
                    altD.setText("Idade Média");
                break;
                
                
                /****           questão 10             ****/                
                case 10:
                if (altB.isSelected()) {
                    pontos = pontos + 1;
                    acertos = acertos+1;
                    
                        /*Mudando de label com msg final*/
                        pergunta.setVisible(false);
                        
                        msgFinal.setText("Parabéns, você ganhou!!");
                        /* */
                        
                        /*deixando as alternativas e o titulo invisiveis*/
                        jtitulo.setVisible(false);
                        altA.setVisible(false);
                        altB.setVisible(false);
                        altC.setVisible(false);
                        altD.setVisible(false);
                        btn.setVisible(false);

                        /* */
                        
                        /*mudando a msg "Vida" para "Acertos", e "Pontos"
                        para "Erros"*/ 
                            /*vida*/
                            
                        jLabel2.setText("ACERTOS:");
                        jVida.setText(Integer.toString(acertos));
                            /* */
                            /*erros*/
                        jLabel3.setText("ERROS:");
                        jPontos.setText(Integer.toString(erros));
                            /* */                       

                } else {
                    vidas = vidas - 1;
                    jVida.setText(Integer.toString(vidas));
                    JOptionPane.showMessageDialog(null, "Você errou!");
                    erros = erros+1;
                    
                    /*Mudando da pergunta para tela final*/
                        pergunta.setVisible(false);
                        msgFinal.setText("Parabéns, você ganhou!!");
                        /* */
                        
                        /*deixando as alternativas e o titulo invisiveis*/
                        jtitulo.setVisible(false);
                        
                        altA.setVisible(false);
                        altB.setVisible(false);
                        altC.setVisible(false);
                        altD.setVisible(false);
                        btn.setVisible(false);  
                        jLabel2.setVisible(false);
                        jVida.setVisible(false);                        
                        jLabel3.setVisible(false);
                        jPontos.setVisible(false);
                        /* */
                        
                       
                    
                    if (vidas==0){                    
                       
                       
                    }
                }
                break;               
        }
    }//GEN-LAST:event_btnActionPerformed

    private void altBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altBActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_altBActionPerformed

    private void altDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altDActionPerformed

    private void altCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pergunta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton altA;
    private javax.swing.JRadioButton altB;
    private javax.swing.JRadioButton altC;
    private javax.swing.JRadioButton altD;
    private javax.swing.JButton btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jPontos;
    private javax.swing.JLabel jVida;
    private javax.swing.JLabel jbackground;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JLabel msgFinal;
    private javax.swing.JLabel pergunta;
    // End of variables declaration//GEN-END:variables
}