/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author 52292234X
 */
public class pergunta2 extends javax.swing.JFrame {

    /**
     * Creates new form pergunta2
     */
    public pergunta2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        j5a = new javax.swing.JRadioButton();
        j5b = new javax.swing.JRadioButton();
        j8b = new javax.swing.JRadioButton();
        j8a = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        j7b = new javax.swing.JRadioButton();
        j7a = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        j6b = new javax.swing.JRadioButton();
        j6a = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jtitulo.setForeground(new java.awt.Color(255, 0, 0));
        jtitulo.setText("PERGUNTAS 2");
        getContentPane().add(jtitulo);
        jtitulo.setBounds(120, 10, 210, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("5 - O que a palavra legend significa em português?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 470, 40);

        j5a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j5a.setForeground(new java.awt.Color(255, 255, 255));
        j5a.setText("Lenda");
        j5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5aActionPerformed(evt);
            }
        });
        getContentPane().add(j5a);
        j5a.setBounds(60, 90, 180, 27);

        j5b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j5b.setForeground(new java.awt.Color(255, 255, 255));
        j5b.setText("Legenda");
        j5b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5bActionPerformed(evt);
            }
        });
        getContentPane().add(j5b);
        j5b.setBounds(60, 120, 180, 27);

        j8b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j8b.setForeground(new java.awt.Color(255, 255, 255));
        j8b.setText("Macau");
        j8b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8bActionPerformed(evt);
            }
        });
        getContentPane().add(j8b);
        j8b.setBounds(60, 390, 180, 27);

        j8a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j8a.setForeground(new java.awt.Color(255, 255, 255));
        j8a.setText("Portugal");
        j8a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8aActionPerformed(evt);
            }
        });
        getContentPane().add(j8a);
        j8a.setBounds(60, 360, 180, 27);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("8 - Em qual local da Ásia o português é língua oficial?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 330, 660, 30);

        j7b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j7b.setForeground(new java.awt.Color(255, 255, 255));
        j7b.setText("Monte Roraima");
        j7b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7bActionPerformed(evt);
            }
        });
        getContentPane().add(j7b);
        j7b.setBounds(60, 300, 180, 27);

        j7a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j7a.setForeground(new java.awt.Color(255, 255, 255));
        j7a.setText("Pico da Neblina");
        j7a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7aActionPerformed(evt);
            }
        });
        getContentPane().add(j7a);
        j7a.setBounds(60, 270, 180, 27);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("7 - Qual a montanha mais alta do Brasil?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 600, 30);

        j6b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j6b.setForeground(new java.awt.Color(255, 255, 255));
        j6b.setText("Idade Média");
        j6b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6bActionPerformed(evt);
            }
        });
        getContentPane().add(j6b);
        j6b.setBounds(60, 210, 180, 27);

        j6a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j6a.setForeground(new java.awt.Color(255, 255, 255));
        j6a.setText("Paleolítico");
        j6a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6aActionPerformed(evt);
            }
        });
        getContentPane().add(j6a);
        j6a.setBounds(60, 180, 180, 27);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("6 - Em que período da pré-história o fogo foi descoberto?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 480, 30);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("VIDAS:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 20, 50, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DSADSAD");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 20, 100, 20);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PONTOS:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(580, 20, 60, 20);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Avançar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 413, 110, 30);

        jbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        getContentPane().add(jbackground);
        jbackground.setBounds(-6, -6, 730, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5aActionPerformed
        // TODO add your handling code here:
        if(j5a.isSelected()){
            j5b.setSelected(false);
        }else{
            j5a.setSelected(false);
        }
    }//GEN-LAST:event_j5aActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                pergunta3 login = new pergunta3();
                login.setVisible(true);
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j5bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5bActionPerformed
        // TODO add your handling code here:
        if(j5b.isSelected()){
            j5a.setSelected(false);
        }else{
            j5b.setSelected(false);
        }
    }//GEN-LAST:event_j5bActionPerformed

    private void j6aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6aActionPerformed
        // TODO add your handling code here:
        
        if(j6a.isSelected()){
            j6b.setSelected(false);
        }else{
            j6a.setSelected(false);
        }
        
        
        
    }//GEN-LAST:event_j6aActionPerformed

    private void j6bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6bActionPerformed
        // TODO add your handling code here:
        
        if(j6b.isSelected()){
            j6a.setSelected(false);
        }else{
            j6b.setSelected(false);
        }
    }//GEN-LAST:event_j6bActionPerformed

    private void j7aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7aActionPerformed
        // TODO add your handling code here:
        
        if(j7a.isSelected()){
            j7b.setSelected(false);
        }else{
            j7a.setSelected(false);
        }
    }//GEN-LAST:event_j7aActionPerformed

    private void j7bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7bActionPerformed
        // TODO add your handling code here:
        
        if(j7b.isSelected()){
            j7a.setSelected(false);
        }else{
            j7b.setSelected(false);
        }
    }//GEN-LAST:event_j7bActionPerformed

    private void j8aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8aActionPerformed
        // TODO add your handling code here:
        
        if(j8a.isSelected()){
            j8b.setSelected(false);
        }else{
            j8a.setSelected(false);
        }
    }//GEN-LAST:event_j8aActionPerformed

    private void j8bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8bActionPerformed
        // TODO add your handling code here:
        
        if(j8b.isSelected()){
            j8a.setSelected(false);
        }else{
            j8b.setSelected(false);
        }
    }//GEN-LAST:event_j8bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If j5abus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pergunta2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton j5a;
    private javax.swing.JRadioButton j5b;
    private javax.swing.JRadioButton j6a;
    private javax.swing.JRadioButton j6b;
    private javax.swing.JRadioButton j7a;
    private javax.swing.JRadioButton j7b;
    private javax.swing.JRadioButton j8a;
    private javax.swing.JRadioButton j8b;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jbackground;
    private javax.swing.JLabel jtitulo;
    // End of variables declaration//GEN-END:variables
}
