/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author 52292234X
 */
public class pergunta3 extends javax.swing.JFrame {

    /**
     * Creates new form pergunta3
     */
    public pergunta3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtitulo = new javax.swing.JLabel();
        j9b = new javax.swing.JRadioButton();
        j9a = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        j10b = new javax.swing.JRadioButton();
        j10a = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbackground1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jtitulo.setForeground(new java.awt.Color(255, 0, 0));
        jtitulo.setText("PERGUNTAS 3");
        getContentPane().add(jtitulo);
        jtitulo.setBounds(120, 10, 210, 40);

        j9b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j9b.setForeground(new java.awt.Color(255, 255, 255));
        j9b.setText("Chikungunya, aids e herpes genital");
        j9b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9bActionPerformed(evt);
            }
        });
        getContentPane().add(j9b);
        j9b.setBounds(60, 120, 250, 27);

        j9a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j9a.setForeground(new java.awt.Color(255, 255, 255));
        j9a.setText("Gonorreia, clamídia e sífilis");
        j9a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9aActionPerformed(evt);
            }
        });
        getContentPane().add(j9a);
        j9a.setBounds(60, 90, 250, 27);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("9 - Quais destas doenças são sexualmente transmissíveis?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 500, 40);

        j10b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j10b.setForeground(new java.awt.Color(255, 255, 255));
        j10b.setText("Rússia, Egito");
        j10b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10bActionPerformed(evt);
            }
        });
        getContentPane().add(j10b);
        j10b.setBounds(60, 210, 180, 27);

        j10a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j10a.setForeground(new java.awt.Color(255, 255, 255));
        j10a.setText("Filipinas, Istambul");
        j10a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10aActionPerformed(evt);
            }
        });
        getContentPane().add(j10a);
        j10a.setBounds(60, 180, 180, 27);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("10 - Qual destes países é transcontinental?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 480, 30);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 263, 90, 30);

        jbackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        getContentPane().add(jbackground1);
        jbackground1.setBounds(0, -10, 730, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j9aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9aActionPerformed
        // TODO add your handling code here:
        if(j9a.isSelected()){
            j9b.setSelected(false);
        }else{
            j9a.setSelected(false);
        }
        
    }//GEN-LAST:event_j9aActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j9bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9bActionPerformed
        // TODO add your handling code here:
        
        if(j9b.isSelected()){
            j9a.setSelected(false);
        }else{
            j9b.setSelected(false);
        }
    }//GEN-LAST:event_j9bActionPerformed

    private void j10aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10aActionPerformed
        // TODO add your handling code here:
        
        if(j10a.isSelected()){
            j10b.setSelected(false);
        }else{
            j10a.setSelected(false);
        }
    }//GEN-LAST:event_j10aActionPerformed

    private void j10bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10bActionPerformed
        // TODO add your handling code here:
        if(j10b.isSelected()){
            j10a.setSelected(false);
        }else{
            j10b.setSelected(false);
        }
    }//GEN-LAST:event_j10bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pergunta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pergunta3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton j10a;
    private javax.swing.JRadioButton j10b;
    private javax.swing.JRadioButton j9a;
    private javax.swing.JRadioButton j9b;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jbackground1;
    private javax.swing.JLabel jtitulo;
    // End of variables declaration//GEN-END:variables
}
