/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author 52292234X
 */
public class pergunta1 extends javax.swing.JFrame {

    /**
     * Creates new form pergunta1
     */
    public pergunta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j1a = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        j1b = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        j2a = new javax.swing.JRadioButton();
        j2b = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        j3a = new javax.swing.JRadioButton();
        j3b = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        j4a = new javax.swing.JRadioButton();
        j4b = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jtitulo.setForeground(new java.awt.Color(255, 0, 0));
        jtitulo.setText("PERGUNTAS");
        getContentPane().add(jtitulo);
        jtitulo.setBounds(120, 10, 140, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VIDAS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 20, 50, 20);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PONTOS:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 20, 60, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DSADSAD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 20, 100, 20);

        j1a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j1a.setForeground(new java.awt.Color(255, 255, 255));
        j1a.setText("2 à 4 Litros");
        j1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1aActionPerformed(evt);
            }
        });
        getContentPane().add(j1a);
        j1a.setBounds(60, 90, 180, 27);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1 - Quantos litros de sangue uma pessoa saúdavel tem?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 470, 40);

        j1b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j1b.setForeground(new java.awt.Color(255, 255, 255));
        j1b.setText("4 à 6 Litros");
        j1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1bActionPerformed(evt);
            }
        });
        getContentPane().add(j1b);
        j1b.setBounds(60, 120, 180, 27);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2 - Quais são os menores países do mundo? ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 370, 30);

        j2a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j2a.setForeground(new java.awt.Color(255, 255, 255));
        j2a.setText("Vaticano e Rússia");
        j2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2aActionPerformed(evt);
            }
        });
        getContentPane().add(j2a);
        j2a.setBounds(60, 180, 180, 27);

        j2b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j2b.setForeground(new java.awt.Color(255, 255, 255));
        j2b.setText("Mônaco e Canadá");
        j2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2bActionPerformed(evt);
            }
        });
        getContentPane().add(j2b);
        j2b.setBounds(60, 210, 180, 27);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("3 - Atualmente, quantos elementos químicos a tabela periódica possui?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 600, 30);

        j3a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j3a.setForeground(new java.awt.Color(255, 255, 255));
        j3a.setText("118");
        j3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3aActionPerformed(evt);
            }
        });
        getContentPane().add(j3a);
        j3a.setBounds(60, 270, 180, 27);

        j3b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j3b.setForeground(new java.awt.Color(255, 255, 255));
        j3b.setText("92");
        j3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3bActionPerformed(evt);
            }
        });
        getContentPane().add(j3b);
        j3b.setBounds(60, 300, 180, 27);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("4 - Quais os países que têm a maior e a menor expectativa de vida do mundo?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 330, 660, 30);

        j4a.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j4a.setForeground(new java.awt.Color(255, 255, 255));
        j4a.setText("Austrália e Afeganistão");
        j4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4aActionPerformed(evt);
            }
        });
        getContentPane().add(j4a);
        j4a.setBounds(60, 360, 180, 27);

        j4b.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        j4b.setForeground(new java.awt.Color(255, 255, 255));
        j4b.setText("Japão e Serra Leoa");
        j4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4bActionPerformed(evt);
            }
        });
        getContentPane().add(j4b);
        j4b.setBounds(60, 390, 180, 27);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Avançar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 413, 101, 30);

        jbackground.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jbackground.setForeground(new java.awt.Color(255, 255, 255));
        jbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        getContentPane().add(jbackground);
        jbackground.setBounds(0, 0, 730, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1aActionPerformed
        // TODO add your handling code here:
        if(j1a.isSelected()){
            j1b.setSelected(false);
        }else{
            j1a.setSelected(false);
        }
            
        
        
    }//GEN-LAST:event_j1aActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                pergunta2 login = new pergunta2();
                login.setVisible(true);
                dispose();      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1bActionPerformed
        // TODO add your handling code here:
        
        if(j1b.isSelected()){
            j1a.setSelected(false);
        }else{
            j1b.setSelected(false);
        }
    }//GEN-LAST:event_j1bActionPerformed

    private void j2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2aActionPerformed
        // TODO add your handling code here:
        
        if(j2a.isSelected()){
            j2b.setSelected(false);
        }else{
            j2a.setSelected(false);
        }
    }//GEN-LAST:event_j2aActionPerformed

    private void j2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2bActionPerformed
        // TODO add your handling code here:
        
        if(j2b.isSelected()){
            j2a.setSelected(false);
        }else{
            j2b.setSelected(false);
        }
    }//GEN-LAST:event_j2bActionPerformed

    private void j3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3aActionPerformed
        // TODO add your handling code here:
        
        if(j3a.isSelected()){
            j3b.setSelected(false);
        }else{
            j3a.setSelected(false);
        }
    }//GEN-LAST:event_j3aActionPerformed

    private void j3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3bActionPerformed
        // TODO add your handling code here:
        
        if(j3b.isSelected()){
            j3a.setSelected(false);
        }else{
            j3b.setSelected(false);
        }
        
        
    }//GEN-LAST:event_j3bActionPerformed

    private void j4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4aActionPerformed
        // TODO add your handling code here:
        
        if(j4a.isSelected()){
            j4b.setSelected(false);
        }else{
            j4a.setSelected(false);
        }
        
        
    }//GEN-LAST:event_j4aActionPerformed

    private void j4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4bActionPerformed
        // TODO add your handling code here:
        
        if(j4b.isSelected()){
            j4a.setSelected(false);
        }else{
            j4b.setSelected(false);
        }
    }//GEN-LAST:event_j4bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pergunta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton j1a;
    private javax.swing.JRadioButton j1b;
    private javax.swing.JRadioButton j2a;
    private javax.swing.JRadioButton j2b;
    private javax.swing.JRadioButton j3a;
    private javax.swing.JRadioButton j3b;
    private javax.swing.JRadioButton j4a;
    private javax.swing.JRadioButton j4b;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jbackground;
    private javax.swing.JLabel jtitulo;
    // End of variables declaration//GEN-END:variables
}
